title: Default Page

tabs:
  content:
    label: Content
    icon: page
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              text:
                type: writer

      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
            template: default
          files:
            type: files

  seo: seo/page
